@Test public void testWrite3() throws Exception {
  this.test1Endpoint.setExpectedCount(2);
  testBody(this.test1Endpoint.message(0),assertGoodValue("Foo1"));
  testBody(this.test1Endpoint.message(1),assertGoodValue("Foo3"));
  this.test2Endpoint.setExpectedCount(2);
  testBody(this.test2Endpoint.message(0),assertGoodValue("Foo2"));
  testBody(this.test2Endpoint.message(1),assertGoodValue("Foo4"));
  sendValue(this.producer1,new Variant("Foo1"));
  sendValue(this.producer2,new Variant("Foo2"));
  sendValue(this.producer3,new Variant("Foo3"));
  sendValue(this.producer4,new Variant("Foo4"));
  assertMockEndpointsSatisfied();
}
