@Test(expected=HadoopIllegalArgumentException.class) public void testEmptyCreateFlag() throws IOException {
  Path p=getTestRootPath(fc,"test/file");
  fc.create(p,EnumSet.noneOf(CreateFlag.class));
  Assert.fail("Excepted exception not thrown");
}
