@Test public void call() throws Exception {
  runnable=new DelegatingSecurityContextRunnable(delegate,securityContext);
  assertWrapped(runnable);
}
