@Test public void testOperationTimeout() throws IOException, InterruptedException {
  long startNs=System.nanoTime();
  try {
    CONN.callerFactory.single().table(TABLE_NAME).row(ROW).operationTimeout(1,TimeUnit.SECONDS).pause(100,TimeUnit.MILLISECONDS).maxAttempts(Integer.MAX_VALUE).action((controller,loc,stub) -> failedFuture()).call().get();
    fail();
  }
 catch (  ExecutionException e) {
    e.printStackTrace();
    assertThat(e.getCause(),instanceOf(RetriesExhaustedException.class));
  }
  long costNs=System.nanoTime() - startNs;
  assertTrue(costNs >= TimeUnit.SECONDS.toNanos(1));
  assertTrue(costNs < TimeUnit.SECONDS.toNanos(2));
}
