public void testInitError() throws Exception {
  Assert.assertEquals(0,dataSource.getCreateErrorCount());
  Throwable error=null;
  try {
    dataSource.init();
  }
 catch (  Throwable e) {
    error=e;
  }
  Assert.assertNotNull(error);
  Assert.assertTrue(dataSource.getCreateErrorCount() > 0);
  dataSource.getCompositeData();
}
