@Test public void error(){
  Observable.<Integer>error(new TestException()).doAfterNext(afterNext).subscribeWith(to).assertFailure(TestException.class);
  assertTrue(values.isEmpty());
}
